name: Cypress
on:
  push:
    branches:
      - master
  # Will run once the PR is opened or a new commit is pushed against it
  pull_request:
    types:
      - opened
      - synchronize
env:
  DRUPAL_URL: ${{ secrets.DRUPAL_URL }}
  BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
  BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
  RESUMATOR_API_KEY: ${{ secrets.RESUMATOR_API_KEY }}
  KLAVIYO_API_KEY: ${{ secrets.KLAVIYO_API_KEY }}
  KLAVIYO_LIST_ID: ${{ secrets.KLAVIYO_LIST_ID }}
  KLAVIYO_LIST_ID_ACQUIA_ENGAGE: ${{ secrets.KLAVIYO_LIST_ID_ACQUIA_ENGAGE }}
  KLAVIYO_LIST_ID_DRUPALCON: ${{ secrets.KLAVIYO_LIST_ID_DRUPALCON }}
  NODE_ENV: ${{ secrets.NODE_ENV }}
  NODE_VERSION: ${{ secrets.NODE_VERSION }}
  PIPEDRIVE_KEY: ${{ secrets.PIPEDRIVE_KEY }}
  WAIT_ON_TIMEOUT: 600000
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    container: cypress/browsers:node12.13.0-chrome78-ff70
    strategy:
      matrix:
        node: [14]
    name: Cypress E2E testing on Node v${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.2
        with:
          check-name: 'Gatsby Build Service - tagd8_gatsby'
          wait-interval: 20 # seconds
      - name: Set build URL
        run: |
          BULID_URL='https://build-'$(curl -s  https://api.github.com/repos/thirdandgrove/thirdandgrove-com-gatsby/commits/master/check-runs | jq '.check_runs[0].external_id')'.gtsb.io'
          echo "${BULID_URL}"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: cypress run --config baseUrl=${BULID_URL}
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 240
