name: Cypress
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    container: cypress/browsers:node12.13.0-chrome78-ff70
    strategy:
      matrix:
        node: [14]
    name: E2E on Node v${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn run test:e2e:ci
          wait-on: 'http://localhost:8000'
