name: Cypress
# Triggers the workflow on push or pull request events
on: [push, pull_request]

env:
  DRUPAL_URL: ${{ secrets.DRUPAL_URL }}
  BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
  BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
  RESUMATOR_API_KEY: ${{ secrets.RESUMATOR_API_KEY }}
  KLAVIYO_API_KEY: ${{ secrets.KLAVIYO_API_KEY }}
  KLAVIYO_LIST_ID: ${{ secrets.KLAVIYO_LIST_ID }}
  KLAVIYO_LIST_ID_ACQUIA_ENGAGE: ${{ secrets.KLAVIYO_LIST_ID_ACQUIA_ENGAGE }}
  KLAVIYO_LIST_ID_DRUPALCON: ${{ secrets.KLAVIYO_LIST_ID_DRUPALCON }}
  NODE_ENV: ${{ secrets.NODE_ENV }}
  NODE_VERSION: ${{ secrets.NODE_VERSION }}
  PIPEDRIVE_KEY: ${{ secrets.PIPEDRIVE_KEY }}

jobs:
  cypress:
    runs-on: ubuntu-16.04
    container: cypress/browsers:node12.13.0-chrome78-ff70
    strategy:
      matrix:
        node: [14]
    name: Cypress E2E testing on Node v${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install jq
        run: apt-get -y install jq

      - name: Get Status of Gatsby Build
        env:
          SHA: ${{ github.sha }}
        run: |
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/script.sh"

          # run script
          "${GITHUB_WORKSPACE}/.github/workflows/script.sh"

      - name: Set build URL
        run: |
          # check CYPRESS_BASE_URL is set
          echo "$CYPRESS_BASE_URL"

        - name: Custom tests 🧪
          uses: cypress-io/github-action@v1
          with:
            command: yarn run cy:run
