name: Cypress
# Triggers the workflow on push or pull request events
on: [push, pull_request]

env:
  DRUPAL_URL: ${{ secrets.DRUPAL_URL }}
  BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
  BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
  RESUMATOR_API_KEY: ${{ secrets.RESUMATOR_API_KEY }}
  KLAVIYO_API_KEY: ${{ secrets.KLAVIYO_API_KEY }}
  KLAVIYO_LIST_ID: ${{ secrets.KLAVIYO_LIST_ID }}
  KLAVIYO_LIST_ID_ACQUIA_ENGAGE: ${{ secrets.KLAVIYO_LIST_ID_ACQUIA_ENGAGE }}
  KLAVIYO_LIST_ID_DRUPALCON: ${{ secrets.KLAVIYO_LIST_ID_DRUPALCON }}
  NODE_ENV: ${{ secrets.NODE_ENV }}
  NODE_VERSION: ${{ secrets.NODE_VERSION }}
  PIPEDRIVE_KEY: ${{ secrets.PIPEDRIVE_KEY }}

jobs:
  cypress:
    runs-on: ubuntu-16.04
    container: cypress/browsers:node12.13.0-chrome78-ff70
    strategy:
      matrix:
        node: [14]
    name: Cypress E2E testing on Node v${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Install jq
        run: apt-get -y install jq
      - name: Get Status of Gatsby Build
        env:
          SHA: ${{ github.sha }}
        run: |
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/script.sh"

          # run script
          "${GITHUB_WORKSPACE}/.github/workflows/script.sh"
      - name: Set build URL
        run: |
          # curl json external_id
          buildUrl=$(curl -s  https://api.github.com/repos/thirdandgrove/thirdandgrove-com-gatsby/commits/${{ github.sha }}/check-runs | jq -c -r '.check_runs[]? | select( .name | contains("Gatsby Build Service - tagd8_gatsby")) | .external_id')

          # set cypress base url
          export CYPRESS_BASE_URL=https://build-$buildUrl.gtsb.io

          # check CYPRESS_BASE_URL is set
          echo "$CYPRESS_BASE_URL"
      # cache NPM modules and Cypress binary folder
      # we can use "package-lock.json" as the key file
      # to make sure we use the precise Cypress version
      # (which is important when using ^ version in package.json)
      # see https://github.com/actions/cache
      - name: Cache NPM and Cypress 📦
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Cypress 📥
        run: npm i cypress

      - name: Cypress tests 🧪
        uses: ./
        with:
          install: false
