name: Cypress
on:
  push:
  workflow_dispatch:

env:
  DRUPAL_URL: ${{ secrets.DRUPAL_URL }}
  BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
  BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
  RESUMATOR_API_KEY: ${{ secrets.RESUMATOR_API_KEY }}
  KLAVIYO_API_KEY: ${{ secrets.KLAVIYO_API_KEY }}
  KLAVIYO_LIST_ID: ${{ secrets.KLAVIYO_LIST_ID }}
  KLAVIYO_LIST_ID_ACQUIA_ENGAGE: ${{ secrets.KLAVIYO_LIST_ID_ACQUIA_ENGAGE }}
  KLAVIYO_LIST_ID_DRUPALCON: ${{ secrets.KLAVIYO_LIST_ID_DRUPALCON }}
  NODE_ENV: ${{ secrets.NODE_ENV }}
  NODE_VERSION: ${{ secrets.NODE_VERSION }}
  PIPEDRIVE_KEY: ${{ secrets.PIPEDRIVE_KEY }}
  WAIT_ON_TIMEOUT: 600000

jobs:
  cypress:
    runs-on: ubuntu-16.04
    container: cypress/browsers:node12.13.0-chrome78-ff70
    strategy:
      matrix:
        node: [14]
    name: Cypress E2E testing on Node v${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          wait-interval: 10 # seconds
          check-name: Gatsby Build Service - tagd8_gatsby # the name of this job
      - name: Set build URL
        run: |
          echo "${{ github.event.pull_request.head.sha }}"
          BULID_URL='https://build-'$(curl -s  https://api.github.com/repos/thirdandgrove/thirdandgrove-com-gatsby/commits/${{ github.event.pull_request.head.sha }}/check-runs | jq '.check_runs[0].external_id')'.gtsb.io'
          echo "${BULID_URL}"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: cypress run --config baseUrl=${BULID_URL}
          wait-on: '${BULID_URL}'
          wait-on-timeout: 240
