name: Cypress
# Triggers the workflow on push or pull request events
on: [push, pull_request]

env:
  DRUPAL_URL: ${{ secrets.DRUPAL_URL }}
  BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
  BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
  RESUMATOR_API_KEY: ${{ secrets.RESUMATOR_API_KEY }}
  KLAVIYO_API_KEY: ${{ secrets.KLAVIYO_API_KEY }}
  KLAVIYO_LIST_ID: ${{ secrets.KLAVIYO_LIST_ID }}
  KLAVIYO_LIST_ID_ACQUIA_ENGAGE: ${{ secrets.KLAVIYO_LIST_ID_ACQUIA_ENGAGE }}
  KLAVIYO_LIST_ID_DRUPALCON: ${{ secrets.KLAVIYO_LIST_ID_DRUPALCON }}
  PIPEDRIVE_KEY: ${{ secrets.PIPEDRIVE_KEY }}
  INSTALL_COMMAND: install --legacy-peer-deps

jobs:
  init:
    name: 'initial scripts'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get -y install jq

      - name: Get Status of Gatsby Build
        env:
          SHA: ${{ github.sha }}
        run: |
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/script.sh"
          # run script
          "${GITHUB_WORKSPACE}/.github/workflows/script.sh"

      - name: Set the CYPRESS_BASE_URL
        run: |
          echo "CYPRESS_BASE_URL=$(curl -s  https://api.github.com/repos/thirdandgrove/thirdandgrove-com-gatsby/commits/$1/check-runs | jq -c -r '.check_runs[]? | select( .name | contains("Gatsby Build Service - tagd8_gatsby")) | .external_id')" >> $GITHUB_ENV

      - name: Test the CYPRESS_BASE_URL
        run: echo $CYPRESS_BASE_URL

  matrix:
    needs: [init]
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.set-matrix.outputs.requireds }}
    steps:
      - uses: ljharb/actions/node/matrix@main
        id: set-matrix
        with:
          preset: '>=12'

  latest:
    needs: [matrix]
    name: 'latest minors'
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.latest) }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        with:
          node-version: ${{ matrix.node-version }}
          skip-install: true
          after_install: nvm install ${{ matrix.node-version }} && npm install --legacy-peer-deps
      - run: npm run cy:run

  node:
    name: 'node'
    needs: [latest]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
